"""D4XX camera CID definitions, device type codes, and stream layout constants."""

from ..v4l2.ioctls import V4L2_CTRL_CLASS_CAMERA

# DS5_DEPTH_STREAM_DT from d4xx.c:96
DS5_DEPTH_STREAM_DT = 0x4000

# CID base: V4L2_CTRL_CLASS_CAMERA | DS5_DEPTH_STREAM_DT
DS5_CAMERA_CID_BASE = V4L2_CTRL_CLASS_CAMERA | DS5_DEPTH_STREAM_DT

# CID offsets from d4xx.c:2124-2151
DS5_CAMERA_CID_LOG = DS5_CAMERA_CID_BASE + 0
DS5_CAMERA_CID_LASER_POWER = DS5_CAMERA_CID_BASE + 1
DS5_CAMERA_CID_MANUAL_LASER_POWER = DS5_CAMERA_CID_BASE + 2
DS5_CAMERA_DEPTH_CALIBRATION_TABLE_GET = DS5_CAMERA_CID_BASE + 3
DS5_CAMERA_DEPTH_CALIBRATION_TABLE_SET = DS5_CAMERA_CID_BASE + 4
DS5_CAMERA_COEFF_CALIBRATION_TABLE_GET = DS5_CAMERA_CID_BASE + 5
DS5_CAMERA_COEFF_CALIBRATION_TABLE_SET = DS5_CAMERA_CID_BASE + 6
DS5_CAMERA_CID_FW_VERSION = DS5_CAMERA_CID_BASE + 7
DS5_CAMERA_CID_GVD = DS5_CAMERA_CID_BASE + 8
DS5_CAMERA_CID_AE_ROI_GET = DS5_CAMERA_CID_BASE + 9
DS5_CAMERA_CID_AE_ROI_SET = DS5_CAMERA_CID_BASE + 10
DS5_CAMERA_CID_AE_SETPOINT_GET = DS5_CAMERA_CID_BASE + 11
DS5_CAMERA_CID_AE_SETPOINT_SET = DS5_CAMERA_CID_BASE + 12
DS5_CAMERA_CID_ERB = DS5_CAMERA_CID_BASE + 13
DS5_CAMERA_CID_EWB = DS5_CAMERA_CID_BASE + 14
DS5_CAMERA_CID_HWMC = DS5_CAMERA_CID_BASE + 15
DS5_CAMERA_CID_SYNC_MODE = DS5_CAMERA_CID_BASE + 16
DS5_CAMERA_CID_PWM = DS5_CAMERA_CID_BASE + 22
DS5_CAMERA_CID_HWMC_RW = DS5_CAMERA_CID_BASE + 32
DS5_CAMERA_CID_HW_RESET = DS5_CAMERA_CID_BASE + 33
DS5_CAMERA_CID_READOUT_SHAPING = DS5_CAMERA_CID_BASE + 34
# Single read/write control for depth AE mode (XU depth selector 0x11).
DS5_CAMERA_CID_AE_MODE = DS5_CAMERA_CID_BASE + 35

# Device type codes from d4xx.c:71-75
DS5_DEVICE_TYPE_D40X = 8
DS5_DEVICE_TYPE_D41X = 7
DS5_DEVICE_TYPE_D45X = 6
DS5_DEVICE_TYPE_D43X = 5

DEVICE_TYPE_NAMES = {
    DS5_DEVICE_TYPE_D40X: "D40X",
    DS5_DEVICE_TYPE_D41X: "D41X",
    DS5_DEVICE_TYPE_D43X: "D43X",
    DS5_DEVICE_TYPE_D45X: "D45X",
}

# Stream index constants (per-camera device layout: 6 devices each)
STREAM_DEPTH = 0
STREAM_DEPTH_MD = 1
STREAM_RGB = 2
STREAM_RGB_MD = 3
STREAM_IR = 4
STREAM_IMU = 5
DEVICES_PER_CAMERA = 6

STREAM_NAMES = {
    STREAM_DEPTH: "Depth",
    STREAM_DEPTH_MD: "Depth Metadata",
    STREAM_RGB: "RGB",
    STREAM_RGB_MD: "RGB Metadata",
    STREAM_IR: "IR",
    STREAM_IMU: "IMU",
}

# Driver names used in QUERYCAP
D4XX_DRIVER_NAME = b"d4xx"
TEGRA_VIDEO_DRIVER_NAME = b"tegra-video"
KNOWN_DRIVER_NAMES = {D4XX_DRIVER_NAME, TEGRA_VIDEO_DRIVER_NAME}
