ARG BASE_IMAGE=ubuntu:18.04 

FROM $BASE_IMAGE as d4xx-build-env

RUN mkdir /src
COPY ./ /src

### Stage 1 - add/remove packages ###
RUN set -eux; apt update \
		&& apt install -y gcc-aarch64-linux-gnu \ 
		build-essential bc xxd wget git kmod \
		&& apt -y clean \
		&& rm -rf /var/lib/apt/lists/*

# direct download method
RUN mkdir /build

WORKDIR /build
RUN \
if [ -f /src/public_sources.tbz2 ]; then \
  cp /src/public_sources.tbz2 .;\
else \
  wget -q https://developer.nvidia.com/embedded/l4t/r32_release_v7.1/sources/t186/public_sources.tbz2; \
fi
RUN tar xjf public_sources.tbz2
WORKDIR /build/Linux_for_Tegra/source/public
RUN tar xjf kernel_src.tbz2

LABEL version="0.0.1"
MAINTAINER "dmitry.perchanov@intel.com"
