k:kernel/kernel-5.10:nv-tegra/linux-5.10.git:
k:kernel/nvgpu:nv-tegra/linux-nvgpu.git:
k:kernel/nvidia:nv-tegra/linux-nvidia.git:
k:kernel/nvidia/drivers/net/ethernet/nvidia/nvethernet/nvethernetrm:nv-tegra/kernel/nvethernetrm.git:
k:hardware/nvidia/platform/tegra/common:nv-tegra/device/hardware/nvidia/platform/tegra/common.git:
k:hardware/nvidia/soc/t19x:nv-tegra/device/hardware/nvidia/soc/t19x.git:
k:hardware/nvidia/platform/t19x/common:nv-tegra/device/hardware/nvidia/platform/t19x/common.git:
k:hardware/nvidia/platform/t19x/galen/kernel-dts:nv-tegra/device/hardware/nvidia/platform/t19x/stardust-dts.git:
k:hardware/nvidia/platform/t19x/jakku/kernel-dts:nv-tegra/device/hardware/nvidia/platform/t19x/jakku-dts.git:
k:hardware/nvidia/platform/t19x/mccoy/kernel-dts:nv-tegra/device/hardware/nvidia/platform/t19x/mccoy-dts.git:
k:hardware/nvidia/platform/t19x/galen-industrial/kernel-dts:nv-tegra/device/hardware/nvidia/platform/t19x/galen-industrial-dts.git:
k:hardware/nvidia/soc/t23x:nv-tegra/device/hardware/nvidia/soc/t23x.git:
k:hardware/nvidia/platform/t23x/common/kernel-dts:nv-tegra/device/hardware/nvidia/platform/t23x/common-dts.git:
k:hardware/nvidia/platform/t23x/p3768/kernel-dts:nv-tegra/device/hardware/nvidia/platform/t23x/p3768-dts.git:
k:hardware/nvidia/platform/t23x/concord/kernel-dts:nv-tegra/device/hardware/nvidia/platform/t23x/concord-dts.git:
k:hardware/nvidia/platform/t23x/prometheus/kernel-dts:nv-tegra/device/hardware/nvidia/platform/t23x/prometheus-dts:
k:hardware/nvidia/soc/tegra:nv-tegra/device/hardware/nvidia/soc/tegra.git:
k:tegra/kernel-src/nv-kernel-display-driver:nv-tegra/tegra/kernel-src/nv-kernel-display-driver.git:
o:3rdparty/libnl/3.5.0:nv-tegra/3rdparty/libnl/3.5.0.git:
o:tegra/argus-cam-libav/argus_cam_libavencoder:nv-tegra/tegra/argus-cam-libav/argus_cam_libavencoder.git:
o:tegra/cuda-src/nvsample_cudaprocess:nv-tegra/tegra/cuda-src/nvsample_cudaprocess.git:
o:tegra/gfx-src/nv-xconfig:nv-tegra/tegra/gfx-src/nv-xconfig.git:
o:tegra/gst-src/gst-egl:nv-tegra/tegra/gst-src/gst-egl.git:
o:tegra/gst-src/gst-jpeg:nv-tegra/tegra/gst-src/gst-jpeg.git:
o:tegra/gst-src/gst-nvarguscamera:nv-tegra/tegra/gst-src/gst-nvarguscamera.git:
o:tegra/gst-src/gst-nvcompositor:nv-tegra/tegra/gst-src/gst-nvcompositor.git:
o:tegra/gst-src/gst-nvtee:nv-tegra/tegra/gst-src/gst-nvtee.git:
o:tegra/gst-src/gst-nvv4l2camera:nv-tegra/tegra/gst-src/gst-nvv4l2camera.git:
o:tegra/gst-src/gst-nvvidconv:nv-tegra/tegra/gst-src/gst-nvvidconv.git:
o:tegra/gst-src/gst-nvvideo4linux2:nv-tegra/tegra/gst-src/gst-nvvideo4linux2.git:
o:tegra/gst-src/nvgstapps:nv-tegra/tegra/gst-src/nvgstapps.git:
o:tegra/gst-src/libgstnvcustomhelper:nv-tegra/tegra/gst-src/libgstnvcustomhelper.git:
o:tegra/gst-src/libgstnvdrmvideosink:nv-tegra/tegra/gst-src/libgstnvdrmvideosink.git:
o:tegra/gst-src/libgstnvvideosinks:nv-tegra/tegra/gst-src/libgstnvvideosinks.git:
o:tegra/v4l2-src/libv4l2_nvargus:nv-tegra/tegra/v4l2-src/libv4l2_nvargus.git:
o:tegra/nv-sci-src/nvsci_headers:nv-tegra/tegra/nv-sci-src/nvsci_headers.git:
o:tegra/optee-src/atf:nv-tegra/tegra/optee-src/atf.git:
o:tegra/optee-src/nv-optee:nv-tegra/tegra/optee-src/nv-optee.git:
o:tegra/v4l2-src/v4l2_libs:nv-tegra/tegra/v4l2-src/v4l2_libs.git:
