k:kernel/kernel-jammy-src:nv-tegra/3rdparty/canonical/linux-jammy.git:
k:nvgpu:nv-tegra/linux-nvgpu.git:
k:nvidia-oot:nv-tegra/linux-nv-oot.git:
k:hwpm:nv-tegra/linux-hwpm.git:
k:nvethernetrm:nv-tegra/kernel/nvethernetrm.git:
k:hardware/nvidia/t23x/nv-public:nv-tegra/device/hardware/nvidia/t23x-public-dts.git:
k:hardware/nvidia/tegra/nv-public:nv-tegra/device/hardware/nvidia/tegra-public-dts.git:
k:nvdisplay:nv-tegra/tegra/kernel-src/nv-kernel-display-driver.git:
k:dtc-src/1.4.5:nv-tegra/3rdparty/dtc-src/1.4.5.git:
o:tegra/argus-cam-libav/argus_cam_libavencoder:nv-tegra/tegra/argus-cam-libav/argus_cam_libavencoder.git:
o:tegra/cuda-src/nvsample_cudaprocess:nv-tegra/tegra/cuda-src/nvsample_cudaprocess.git:
o:tegra/gfx-src/nv-xconfig:nv-tegra/tegra/gfx-src/nv-xconfig.git:
o:tegra/gst-src/gst-egl:nv-tegra/tegra/gst-src/gst-egl.git:
o:tegra/gst-src/gst-jpeg:nv-tegra/tegra/gst-src/gst-jpeg.git:
o:tegra/gst-src/gst-nvarguscamera:nv-tegra/tegra/gst-src/gst-nvarguscamera.git:
o:tegra/gst-src/gst-nvcompositor:nv-tegra/tegra/gst-src/gst-nvcompositor.git:
o:tegra/gst-src/gst-nvtee:nv-tegra/tegra/gst-src/gst-nvtee.git:
o:tegra/gst-src/gst-nvv4l2camera:nv-tegra/tegra/gst-src/gst-nvv4l2camera.git:
o:tegra/gst-src/gst-nvvidconv:nv-tegra/tegra/gst-src/gst-nvvidconv.git:
o:tegra/gst-src/gst-nvvideo4linux2:nv-tegra/tegra/gst-src/gst-nvvideo4linux2.git:
o:tegra/gst-src/nvgstapps:nv-tegra/tegra/gst-src/nvgstapps.git:
o:tegra/gst-src/libgstnvcustomhelper:nv-tegra/tegra/gst-src/libgstnvcustomhelper.git:
o:tegra/gst-src/libgstnvdrmvideosink:nv-tegra/tegra/gst-src/libgstnvdrmvideosink.git:
o:tegra/gst-src/libgstnvvideosinks:nv-tegra/tegra/gst-src/libgstnvvideosinks.git:
o:tegra/v4l2-src/libv4l2_nvargus:nv-tegra/tegra/v4l2-src/libv4l2_nvargus.git:
o:tegra/nv-sci-src/nvsci_headers:nv-tegra/tegra/nv-sci-src/nvsci_headers.git:
o:tegra/optee-src/atf:nv-tegra/tegra/optee-src/atf.git:
o:tegra/optee-src/nv-optee:nv-tegra/tegra/optee-src/nv-optee.git:
o:tegra/v4l2-src/v4l2_libs:nv-tegra/tegra/v4l2-src/v4l2_libs.git:
